### ISSUE TITLE
Immidiate exit with "Done" status, no downloads

### ISSUE THREAD

**Issue by badarotti** [jjangga0214/sd-models-downloader#4]
Hi, Thanks for making this notebook. Might save a lot of time.

I'm using a RunPod.io container with a persistent network volume. I git cloned the down-loader in the `\workspace` forlder, the notebook runs without error but nothing is downloaded. Also any custom URLs in type in gets reset.

What should I check for?

Thanks

**Comment by jjangga0214** [comment]
Hi! 

Have you tried closing and restart?

Would you please attach screenshot?

Thanks

**Comment by jjangga0214** [comment]
Closing due to no response. 
Feel free to reopen if needed.
Thanks.
